name: Idea
description: Suggest something to improve app
labels: Idea, Needs review
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your idea
      description: How can Breezy Weather be improved for the community? Suggest only one idea at a time (open a new issue for a different idea).
      placeholder: |
        Example:
          "Here is how it should work: …"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you don’t read this carefully.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: The idea I’m suggesting is not in the [list of features that will not be implemented](https://github.com/breezy-weather/breezy-weather/blob/main/README.md#features-that-will-not-be-implemented).
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to **[version 5.2.0 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
          required: true
        - label: I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.
          required: true
